###
GET  http://localhost:5000 HTTP/1.1
Content-Type: application/json

###
# Authorization: atighloveljene eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJhdGlnaCIsImVtYWlsIjoiZWxhdGlnaEBEUzI0LmNvbSIsInVzZXJuYW1lIjoiYXRpZ2giLCJpYXQiOjE2MjUxNDM2NjMsImV4cCI6MTYyNTE0NDI2M30.5m-AJcB5WIDS8iGgHZOFMXKcadtZbAR817IdCvnBMk8
POST  http://localhost:5000/houses HTTP/1.1
Content-Type: application/json

{
    "property_type":"", 
    "add_type":"",
    "rent_type":"",
    "region":"",
    "city":"",
    "street_size":"",
    "price":"",
    "number_of_room":"",
    "number_of_bathroom":"",
    "number_of_kitchen":"",
    "has_car_park":"",
    "number_of_floors":"",
    "has_furniture":"",
    "images":"",
    "description":""
}
###
PUT http://localhost:5000/houses/update-house/2  HTTP/1.1
Content-Type: application/json

{
    "property_type":"Maison", 
    "add_type":"Louer",
    "rent_type":"Par Mois",
    "region":"NOUAKCHOTT SID",
    "city":"ARAVAT",
    "street_size":800,
    "price":12000,
    "number_of_room":7,
    "number_of_bathroom":3,
    "number_of_kitchen":2,
    "has_car_park":true,
    "number_of_floors":2,
    "has_furniture":true,
    "images":"blalalla",
    "description":"description"
}
####
DELETE  http://localhost:5000/houses/delete-house/2  HTTP/1.1
Content-Type: application/json
####
DELETE  http://localhost:5000/apartments/delete-apartment/ HTTP/1.1
Content-Type: application/json
####
DELETE  http://localhost:5000/lands/delete-land/2  HTTP/1.1
####
Content-Type: application/json
DELETE  http://localhost:5000/stores/delete-store/5  HTTP/1.1
Content-Type: application/json
####
POST  http://localhost:3333/api/v1/auth/login  HTTP/1.1
Content-Type: application/json

{
   "email":"elatigh@DS24.com", 
    "password":"atigh"
}
####


GET http://localhost:3333/api/v1/auth/users  HTTP/1.1
Content-Type: application/json


####
POST http://localhost:3333/api/v1/auth/sign-up  HTTP/1.1
Content-Type: application/json

{
    "name":"atigh", 
    "email":"elatigh@DS24.com", 
    "password":"atigh", 
    "username":"etfaghaoubeid"
}
###
GET http://localhost:3333/api/v1/auth/logout  HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3333/api/v1/phones/add-accessory  HTTP/1.1
Content-Type: application/json

{
    "image":"image url",
    "name":"name",
    "brand":"brand",
    "isUsed":false,
    "memory":255,
    "price":3444,
    "description":"description",
    "inStock":true
}
####
GET http://localhost:3333/api/v1/accesories HTTP/1.1
Content-Type: application/json

####
GET http://localhost:3333/api/v1/accesories/2 HTTP/1.1
Content-Type: application/json

####

DELETE  http://localhost:3333/api/v1/accesories/4  HTTP/1.1
Content-Type: application/json

####